### ISSUE TITLE
when I build, code doesn't show up

### ISSUE THREAD

**Issue by ChipNowacek** [phillord/tawny-tutorial#1]
I found a typo for which I wanted to offer a pull request. While `make` works, the resulting html doesn't have the source examples. Any ideas?
![screen shot 2017-03-23 at 10 03 17 am](https://cloud.githubusercontent.com/assets/3668197/24251279/00eb0ce6-0fb0-11e7-8faa-839fcae76082.png)

**Comment by phillord** [comment]
asciidoc uses gnu source highlight to syntax highlight the code. 

http://www.methods.co.nz/asciidoc/source-highlight-filter.html

If you haven't installed gnu source highlight it does just drop the source out. I think asciidoc should handle this better, but it doesn't am afraid.

**Comment by ChipNowacek** [comment]
Cool. That worked. Thanks.
